# Permalinks
permalink:           pretty

# Setup
title:               Poole
tagline:             The Jekyll Butler
url:                 http://getpoole.com
paginate:            1
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Alexey Kurakin
  url:               http://kurakin.me
  email:             alexey@kurakin.me

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
